return {
  'echasnovski/mini.move',
  version = '*',
  keys = {
    { '<D-S-j>', "<cmd>lua MiniMove.move_line('down')<cr>" },
    { '<D-S-k>', "<cmd>lua MiniMove.move_line('up')<cr>" },
    { '<D-S-j>', "<cmd>lua MiniMove.move_selection('down')<cr>", mode = 'x' },
    { '<D-S-k>', "<cmd>lua MiniMove.move_selection('up')<cr>", mode = 'x' },
    { '<D-S-h>', "<cmd>lua MiniMove.move_line('left')<cr>" },
    { '<D-S-l>', "<cmd>lua MiniMove.move_line('right')<cr>" },
    { '<D-S-h>', "<cmd>lua MiniMove.move_selection('left')<cr>", mode = 'x' },
    { '<D-S-l>', "<cmd>lua MiniMove.move_selection('right')<cr>", mode = 'x' },

    { '<D-S-Down>', "<cmd>lua MiniMove.move_line('down')<cr>" },
    { '<D-S-Up>', "<cmd>lua MiniMove.move_line('up')<cr>" },
    { '<D-S-Down>', "<cmd>lua MiniMove.move_selection('down')<cr>", mode = 'x' },
    { '<D-S-Up>', "<cmd>lua MiniMove.move_selection('up')<cr>", mode = 'x' },
    { '<D-S-Left>', "<cmd>lua MiniMove.move_line('left')<cr>" },
    { '<D-S-Right>', "<cmd>lua MiniMove.move_line('right')<cr>" },
    { '<D-S-Left>', "<cmd>lua MiniMove.move_selection('left')<cr>", mode = 'x' },
    { '<D-S-Right>', "<cmd>lua MiniMove.move_selection('right')<cr>", mode = 'x' },
  },
  opts = {
    mappings = {
      left = '',
      right = '',
      down = '',
      up = '',
      line_left = '',
      line_right = '',
      line_down = '',
      line_up = '',
    },
  },
}
