tap "jnsahaj/lumen"
brew "jnsahaj/lumen/lumen"

tap "neovim/neovim"
brew "neovim/neovim/neovim", args: ["HEAD"]

brew "carapace"
brew "chezmoi"
brew "mise"
brew "mpv"
brew "msedit"
brew "sk"
brew "streamlink"
brew "tree"
brew "zsh-syntax-highlighting"
cask "docker-desktop"
cask "font-intel-one-mono"
cask "google-chrome"
cask "kitty"
cask "licecap"
cask "spotify"
# https://github.com/2bc4/streamlink-ttvlol
cask "streamlink-twitch-gui"
