[general]
import = [
  "~/.local/share/nvim/lazy/tokyonight.nvim/extras/alacritty/tokyonight_night.toml",
]

[window]
decorations = "None"
startup_mode = "Maximized"
option_as_alt = "Both"

[window.padding]
x = 210
y = 0

[cursor.style]
blinking = "Always"

[font]
size = 15

[font.normal]
family = "Intel One Mono"

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"

[[keyboard.bindings]]
key = 'Enter'
mods = 'Super'
action = 'ToggleMaximized'
