[general]
working_directory = "~"
import = [
  "~/.local/share/nvim/lazy/tokyonight.nvim/extras/alacritty/tokyonight_night.toml",
]

[window]
decorations = "None"
startup_mode = "Maximized"

[font]
size = 15

[font.normal]
family = "IntoneMono Nerd Font Mono"

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"
